### ISSUE TITLE
Getting queue empty when using multiple workers

### ISSUE THREAD

**Issue by jonascript** [scttnlsn/monq#55] opened 2015-10-27 17:37 UTC
Hello
I have a queue of about 90K, (30K with status "queued"). When I set more than a handle of workers to start processing the queue, a lot of them emit empty events. Is there a limit to the number of workers I should be starting?

**Comment by scttnlsn** [comment] 2015-10-27 17:53
This definitely sounds like a bug and may be related to (or a duplicate of) https://github.com/scttnlsn/monq/pull/52

**Comment by jonascript** [comment] 2015-10-27 18:44
Thanks for the quick reply. This definitely seems to be it.

**Comment by scttnlsn** [comment] 2015-12-04 12:24
@jonascript What version are you using?

@trsouz reports (in https://github.com/scttnlsn/monq/pull/52) that he no longer had this problem after upgrading to v3.3. @trsouz Is that correct?

**Comment by trsouz** [comment] 2015-12-04 13:33
Yes @scttnlsn, has no more problems! @jonascript if you are already using the v0.3.3 version could post some of the tasks of your "worker"? Would I like to help to understand this problem.

**Comment by scttnlsn** [comment] 2016-05-20 14:36
Please re-open if this is still an issue.

**Closed by scttnlsn** 2016-05-20 14:36 UTC
